POST http://127.0.0.1:7000/user/register/
Content-Type: application/json

{
    "email": "madhurmongia33@gmail.com",
    "user_name": "dev1",
    "password": "test@gmail.com",
    "password2": "test@gmail.com"
}
###
POST http://127.0.0.1:7000/user/login/
Content-Type: application/json

{
    "email": "madhurmongia33@gmail.com",
    "password": "test@gmail.com"
}

###
GET http://127.0.0.1:7000/user/verify/2c5471051c282dde6d7a18d4f37b28cfd25cf533
###
GET http://127.0.0.1:7000/posts?page=3&category=tech
Authorization: Token a0908159ff6ecbb3cc726afcf916b709907afe99

###
GET http://127.0.0.1:7000/post/tech/patreon-cpo-says-the-company-will-double-in-size-in-2022
Authorization: Token a0908159ff6ecbb3cc726afcf916b709907afe99
###
GET http://127.0.0.1:7000/scrape
