# Generated by Django 4.0 on 2021-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyPost',
            fields=[
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField()),
                ('source', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketPost',
            fields=[
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField()),
                ('source', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsPost',
            fields=[
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField()),
                ('source', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TechPost',
            fields=[
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
                ('date_created', models.DateField(null=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('source', models.URLField()),
            ],
        ),
    ]
