# Generated by Django 4.0 on 2021-12-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techpost',
            name='date_created',
            field=models.DateField(),
        ),
    ]
