# Generated by Django 4.0 on 2021-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpost',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
