# Generated by Django 4.0 on 2021-12-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_marketpost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportspost',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
