# Generated by Django 3.2.10 on 2021-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211222_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economypost',
            name='slug',
            field=models.SlugField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='marketpost',
            name='slug',
            field=models.SlugField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sportspost',
            name='slug',
            field=models.SlugField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='techpost',
            name='slug',
            field=models.SlugField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
